// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abwxamlcnmuulaoeelrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFid3hhbWxjbm11dWxhb2VlbHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNTUxNzQsImV4cCI6MjA1NzgzMTE3NH0.BKs0k1jrz_3rw5iz7KqFx6k8tzvObsAvaKuLhK8TKU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);